version: '3.8'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: backend_challenge
        ports:
            - "8000:80"
        volumes:
            - .:/var/www/html
        environment:
            - APP_ENV=local
            - APP_DEBUG=true
            - APP_KEY=base64:xQ++dtAj2RTkw67wggICsMrxH0naG2RJe1smIsM/8Sg=
            - DB_CONNECTION=mysql
            - DB_HOST=db
            - DB_PORT=3306
            - DB_DATABASE=backend_challenge
            - DB_USERNAME=root
            - DB_PASSWORD=
        depends_on:
            - db

    db:
        image: mysql:8.0
        container_name: mysql_db
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: backend_challenge
            MYSQL_USER: root
            MYSQL_PASSWORD:
        ports:
            - "3307:3306"
        volumes:
            - db_data:/var/lib/mysql

    composer:
        image: composer:2.5
        container_name: composer_install
        volumes:
            - .:/var/www/html
        command: install

volumes:
    db_data:
